import type {
  Category,
  Comment,
  Discussion,
  EventItem,
  Member,
  Notification,
  NotificationPreference,
  Post,
  Submission,
} from "./types";
import { DEFAULT_PREFERENCES } from "./types";

export const categories: Category[] = [
  { id: "cat-news-announcements", name: "Announcements", type: "news" },
  { id: "cat-news-committee", name: "Committee", type: "news" },
  { id: "cat-news-membership", name: "Membership", type: "news" },
  { id: "cat-news-events", name: "Events", type: "news" },
  { id: "cat-news-community", name: "Community", type: "news" },
  { id: "cat-disc-facilities", name: "Facilities", type: "discussion" },
  { id: "cat-disc-events", name: "Events & Social", type: "discussion" },
  { id: "cat-disc-practice", name: "Practice & Training", type: "discussion" },
  { id: "cat-disc-questions", name: "Questions", type: "discussion" },
  { id: "cat-disc-recommendations", name: "Recommendations", type: "discussion" },
  { id: "cat-disc-general", name: "General", type: "both" },
];

export const demoUsers: Member[] = [
  {
    id: "user-sarah",
    name: "Sarah Mitchell",
    role: "member",
    bio: "EFT practitioner based in Bristol. Particularly interested in anxiety work and community peer support.",
    location: "Bristol",
    interests: ["Anxiety support", "Peer groups", "Training"],
    memberSince: "2019-03-12",
    avatarColor: "#2B6CB0",
    initials: "SM",
  },
  {
    id: "user-david",
    name: "David Williams",
    role: "author",
    bio: "Communications lead for the association. Writes newsletters and keeps members informed of official updates.",
    location: "Manchester",
    interests: ["Communications", "Events", "Membership"],
    memberSince: "2015-06-01",
    avatarColor: "#0B2C4A",
    initials: "DW",
  },
  {
    id: "user-helen",
    name: "Helen Carter",
    role: "moderator",
    bio: "Long-standing member and volunteer moderator. Helps keep discussions welcoming and on-topic.",
    location: "Leeds",
    interests: ["Moderation", "Community building", "Workshops"],
    memberSince: "2014-09-18",
    avatarColor: "#15803D",
    initials: "HC",
  },
  {
    id: "user-michael",
    name: "Michael Thompson",
    role: "admin",
    bio: "Association administrator. Oversees membership records, events planning and platform operations.",
    location: "London",
    interests: ["Governance", "Events", "Member services"],
    memberSince: "2012-01-10",
    avatarColor: "#1E3A5F",
    initials: "MT",
  },
];

const additionalMembers: Member[] = [
  {
    id: "user-emma",
    name: "Emma Clarke",
    role: "member",
    bio: "Newly accredited practitioner focusing on workplace stress and burnout.",
    location: "Birmingham",
    interests: ["Workplace stress", "Accreditation"],
    memberSince: "2023-02-14",
    avatarColor: "#0891B2",
    initials: "EC",
  },
  {
    id: "user-james",
    name: "James Patel",
    role: "member",
    bio: "Runs a small practice in Cardiff and enjoys mentoring newer members.",
    location: "Cardiff",
    interests: ["Mentoring", "Clinical practice"],
    memberSince: "2018-11-03",
    avatarColor: "#7C3AED",
    initials: "JP",
  },
  {
    id: "user-olivia",
    name: "Olivia Bennett",
    role: "member",
    bio: "Specialises in working with young people and school-based programmes.",
    location: "Edinburgh",
    interests: ["Young people", "Education"],
    memberSince: "2020-05-22",
    avatarColor: "#DB2777",
    initials: "OB",
  },
  {
    id: "user-thomas",
    name: "Thomas Nguyen",
    role: "member",
    bio: "Interested in research and evidence-based approaches within the association.",
    location: "Cambridge",
    interests: ["Research", "Evidence base"],
    memberSince: "2017-08-09",
    avatarColor: "#EA580C",
    initials: "TN",
  },
  {
    id: "user-chloe",
    name: "Chloe Richards",
    role: "member",
    bio: "Volunteer for regional meet-ups in the South West.",
    location: "Exeter",
    interests: ["Regional groups", "Networking"],
    memberSince: "2021-01-30",
    avatarColor: "#0F766E",
    initials: "CR",
  },
  {
    id: "user-benjamin",
    name: "Benjamin Foster",
    role: "member",
    bio: "Experienced trainer offering introductory workshops for new members.",
    location: "Oxford",
    interests: ["Training", "Workshops"],
    memberSince: "2016-04-17",
    avatarColor: "#B45309",
    initials: "BF",
  },
  {
    id: "user-amelia",
    name: "Amelia Hughes",
    role: "member",
    bio: "Practises in Belfast and is keen to see more regional events in Northern Ireland.",
    location: "Belfast",
    interests: ["Regional events", "Trauma work"],
    memberSince: "2019-10-05",
    avatarColor: "#4F46E5",
    initials: "AH",
  },
  {
    id: "user-lucas",
    name: "Lucas Grant",
    role: "member",
    bio: "Works with sports clients and performance anxiety.",
    location: "Glasgow",
    interests: ["Performance", "Sports"],
    memberSince: "2022-07-19",
    avatarColor: "#0369A1",
    initials: "LG",
  },
  {
    id: "user-isla",
    name: "Isla Morrison",
    role: "member",
    bio: "Committee member for membership engagement and welcome packs.",
    location: "York",
    interests: ["Membership", "Welcome programmes"],
    memberSince: "2015-12-01",
    avatarColor: "#BE185D",
    initials: "IM",
  },
  {
    id: "user-noah",
    name: "Noah Ellis",
    role: "member",
    bio: "Recently relocated from Australia and looking to connect with UK practitioners.",
    location: "Brighton",
    interests: ["Networking", "International practice"],
    memberSince: "2024-01-08",
    avatarColor: "#65A30D",
    initials: "NE",
  },
  {
    id: "user-grace",
    name: "Grace Okonkwo",
    role: "member",
    bio: "Integrates EFT with counselling work in a busy London clinic.",
    location: "London",
    interests: ["Counselling", "Integration"],
    memberSince: "2018-03-27",
    avatarColor: "#9333EA",
    initials: "GO",
  },
  {
    id: "user-harry",
    name: "Harry Sutton",
    role: "member",
    bio: "Helps organise the annual conference and enjoys volunteering at events.",
    location: "Nottingham",
    interests: ["Conference", "Volunteering"],
    memberSince: "2016-09-14",
    avatarColor: "#C2410C",
    initials: "HS",
  },
  {
    id: "user-freya",
    name: "Freya Walsh",
    role: "member",
    bio: "Focuses on grief and bereavement support using EFT.",
    location: "Liverpool",
    interests: ["Grief support", "Peer supervision"],
    memberSince: "2020-11-11",
    avatarColor: "#0E7490",
    initials: "FW",
  },
  {
    id: "user-oscar",
    name: "Oscar Byrne",
    role: "member",
    bio: "Rural practitioner covering a wide area of County Cork and surrounding districts.",
    location: "Cork",
    interests: ["Rural practice", "Community outreach"],
    memberSince: "2017-05-06",
    avatarColor: "#166534",
    initials: "OB",
  },
  {
    id: "user-maya",
    name: "Maya Singh",
    role: "member",
    bio: "Runs online sessions and is interested in digital practice standards.",
    location: "Reading",
    interests: ["Online practice", "Standards"],
    memberSince: "2021-06-20",
    avatarColor: "#A21CAF",
    initials: "MS",
  },
  {
    id: "user-ethan",
    name: "Ethan Brooks",
    role: "member",
    bio: "Former committee treasurer with a keen interest in association finance transparency.",
    location: "Sheffield",
    interests: ["Governance", "Finance"],
    memberSince: "2013-02-28",
    avatarColor: "#1D4ED8",
    initials: "EB",
  },
  {
    id: "user-lily",
    name: "Lily Chapman",
    role: "member",
    bio: "New member exploring accreditation pathways and supervision options.",
    location: "Norwich",
    interests: ["Accreditation", "Supervision"],
    memberSince: "2025-04-02",
    avatarColor: "#E11D48",
    initials: "LC",
  },
  {
    id: "user-jacob",
    name: "Jacob Reed",
    role: "member",
    bio: "Works primarily with veterans and first responders.",
    location: "Plymouth",
    interests: ["Trauma", "Veterans"],
    memberSince: "2019-07-15",
    avatarColor: "#334155",
    initials: "JR",
  },
  {
    id: "user-sophia",
    name: "Sophia Grant",
    role: "member",
    bio: "Coordinates the association book club and quarterly reading circles.",
    location: "Bath",
    interests: ["Book club", "Continuing education"],
    memberSince: "2018-08-21",
    avatarColor: "#7E22CE",
    initials: "SG",
  },
  {
    id: "user-william",
    name: "William Hartley",
    role: "member",
    bio: "Long-time member who remembers the early association newsletters fondly.",
    location: "Chester",
    interests: ["History", "Mentoring"],
    memberSince: "2011-10-03",
    avatarColor: "#475569",
    initials: "WH",
  },
  {
    id: "user-aria",
    name: "Aria Coleman",
    role: "member",
    bio: "Passionate about diversity and inclusion within the membership community.",
    location: "Leicester",
    interests: ["Inclusion", "Community"],
    memberSince: "2022-03-09",
    avatarColor: "#B91C1C",
    initials: "AC",
  },
  {
    id: "user-daniel",
    name: "Daniel Price",
    role: "member",
    bio: "Offers supervision groups and is open to co-facilitating workshops.",
    location: "Newcastle",
    interests: ["Supervision", "Facilitation"],
    memberSince: "2016-01-25",
    avatarColor: "#0F766E",
    initials: "DP",
  },
  {
    id: "user-ruby",
    name: "Ruby Jensen",
    role: "member",
    bio: "Moved from Denmark last year and is building a UK-based client practice.",
    location: "Southampton",
    interests: ["International members", "Practice building"],
    memberSince: "2024-09-16",
    avatarColor: "#C026D3",
    initials: "RJ",
  },
  {
    id: "user-george",
    name: "George Atkinson",
    role: "member",
    bio: "Helps maintain the association library of training materials.",
    location: "Derby",
    interests: ["Resources", "Training materials"],
    memberSince: "2014-04-08",
    avatarColor: "#1E40AF",
    initials: "GA",
  },
  {
    id: "user-nina",
    name: "Nina Farouk",
    role: "member",
    bio: "Interested in culturally sensitive practice and multilingual resources.",
    location: "Bradford",
    interests: ["Cultural competence", "Resources"],
    memberSince: "2020-02-17",
    avatarColor: "#B45309",
    initials: "NF",
  },
  {
    id: "user-callum",
    name: "Callum Davies",
    role: "member",
    bio: "Organises occasional walking meet-ups for members in South Wales.",
    location: "Swansea",
    interests: ["Walking group", "Wellbeing"],
    memberSince: "2021-09-29",
    avatarColor: "#15803D",
    initials: "CD",
  },
];

export const members: Member[] = [...demoUsers, ...additionalMembers];

export const posts: Post[] = [
  {
    id: "post-1",
    title: "Annual General Meeting announced for 18 October",
    summary:
      "Members are invited to attend the AGM at the association headquarters in London, with remote attendance available.",
    body: "We are pleased to announce that this year's Annual General Meeting will take place on Saturday 18 October at 10:00 at Association House, London. Remote attendance will be available via a secure link sent to registered members closer to the date.\n\nThe agenda will include the annual report, financial statements, committee elections and a short Q&A. Please register your attendance by 4 October so we can prepare materials and seating.\n\nProxy voting forms are available from the Members area. If you have questions ahead of the meeting, please contact the secretary.",
    authorId: "user-david",
    date: "2026-09-12T09:00:00.000Z",
    categoryId: "cat-news-announcements",
    status: "published",
    isAnnouncement: true,
  },
  {
    id: "post-2",
    title: "Committee update: September summary",
    summary:
      "A brief overview of recent committee decisions on training pathways, regional groups and the conference venue.",
    body: "The committee met on 2 September. Key points from the meeting:\n\n• Training pathway documentation will be refreshed for 2027 intake.\n• Three new regional coordinators have been appointed for Scotland, Wales and the South West.\n• The 2027 conference venue shortlist has been narrowed to two cities; a final decision is expected in November.\n\nFull minutes will be published after formal approval at the next meeting.",
    authorId: "user-david",
    date: "2026-09-08T14:30:00.000Z",
    categoryId: "cat-news-committee",
    status: "published",
  },
  {
    id: "post-3",
    title: "New membership information for 2027",
    summary:
      "Renewal dates, fee structure and what is included in your membership for the coming year.",
    body: "Membership renewals for 2027 open on 1 November. Fees remain unchanged for the coming year. Your membership continues to include access to this information hub, discounted workshop rates, the quarterly newsletter and voting rights at the AGM.\n\nStudent and retired member rates are still available. If your circumstances have changed, please update your details before renewing.",
    authorId: "user-david",
    date: "2026-09-05T11:00:00.000Z",
    categoryId: "cat-news-membership",
    status: "published",
  },
  {
    id: "post-4",
    title: "Summer Social — thank you and photos",
    summary:
      "A warm thank you to everyone who joined us in July. Photos and a short write-up are now available.",
    body: "Over 120 members attended the Summer Social in Bath. It was a wonderful afternoon of conversation, light workshops and networking. Thank you to the volunteers who made the day possible.\n\nA photo gallery and short write-up are available in the Events section. We hope to see even more of you next year.",
    authorId: "user-david",
    date: "2026-08-02T16:00:00.000Z",
    categoryId: "cat-news-events",
    status: "published",
  },
  {
    id: "post-5",
    title: "Important maintenance notice: Association House",
    summary:
      "Building works will temporarily affect access to the members' lounge and ground-floor meeting rooms.",
    body: "From Monday 13 October to Friday 24 October, Association House will undergo essential electrical and accessibility works. The members' lounge and ground-floor meeting rooms will be closed during this period.\n\nStaff offices on the first floor remain open by appointment. Online services are unaffected. We apologise for any inconvenience.",
    authorId: "user-michael",
    date: "2026-09-20T08:00:00.000Z",
    categoryId: "cat-news-announcements",
    status: "published",
    isAnnouncement: true,
  },
  {
    id: "post-6",
    title: "Association newsletter — Autumn edition",
    summary:
      "Practitioner spotlights, upcoming workshops, research notes and regional news in this quarter's newsletter.",
    body: "The Autumn newsletter is now available. In this edition: a practitioner spotlight with Grace Okonkwo, dates for winter workshops, a short research note from Thomas Nguyen, and updates from regional coordinators.\n\nYou can read the newsletter here in the News section. Printed copies will be posted to members who have opted in.",
    authorId: "user-david",
    date: "2026-09-15T10:00:00.000Z",
    categoryId: "cat-news-community",
    status: "published",
  },
  {
    id: "post-7",
    title: "Changes to Association House opening hours",
    summary:
      "From November, weekday opening hours will adjust slightly to better match member demand.",
    body: "Following feedback from members and staff, Association House weekday opening hours will change from 3 November:\n\nMonday–Thursday: 09:00–17:30\nFriday: 09:00–16:00\n\nWeekend workshop bookings are unaffected. Please plan visits accordingly.",
    authorId: "user-michael",
    date: "2026-09-18T12:00:00.000Z",
    categoryId: "cat-news-announcements",
    status: "published",
  },
  {
    id: "post-8",
    title: "Community update: new peer supervision circles",
    summary:
      "Three new peer supervision circles are forming for late 2026 — spaces are limited.",
    body: "We are pleased to confirm three new peer supervision circles starting in November: one online (Tuesday evenings), one in Manchester (Wednesday mornings) and one in London (Thursday evenings).\n\nEach circle will have a maximum of eight participants. If you would like to join, please submit an expression of interest via the Members area before 20 October.",
    authorId: "user-helen",
    date: "2026-09-22T09:30:00.000Z",
    categoryId: "cat-news-community",
    status: "published",
  },
];

export const discussions: Discussion[] = [
  {
    id: "disc-1",
    title: "Has anyone used the new Association House facilities?",
    body: "I visited Association House last week after the lounge refresh. The new seating is much more comfortable. Has anyone booked the smaller meeting rooms yet? Any tips on which ones work best for supervision pairs?",
    authorId: "user-emma",
    date: "2026-09-21T10:15:00.000Z",
    categoryId: "cat-disc-facilities",
    followers: ["user-emma", "user-sarah", "user-chloe"],
    updatedAt: "2026-09-24T14:20:00.000Z",
  },
  {
    id: "disc-2",
    title: "Suggestions for the summer event",
    body: "Planning for next year's Summer Social is starting early. What would you like to see? More informal networking time, short skill shares, or something completely different?",
    authorId: "user-harry",
    date: "2026-09-19T16:40:00.000Z",
    categoryId: "cat-disc-events",
    followers: ["user-harry", "user-david", "user-isla", "user-callum"],
    updatedAt: "2026-09-25T09:10:00.000Z",
  },
  {
    id: "disc-3",
    title: "Anyone interested in organising a walking group?",
    body: "A few of us in South Wales have been chatting about a gentle monthly walking group for members — nothing formal, just fresh air and conversation. Would anyone else be interested, elsewhere in the UK too?",
    authorId: "user-callum",
    date: "2026-09-17T08:50:00.000Z",
    categoryId: "cat-disc-general",
    followers: ["user-callum", "user-sarah", "user-amelia"],
    updatedAt: "2026-09-23T11:05:00.000Z",
  },
  {
    id: "disc-4",
    title: "Question about next month's meeting",
    body: "Is the October regional meeting in Birmingham still going ahead on the 12th? I need to book travel and wanted to confirm before I do.",
    authorId: "user-lily",
    date: "2026-09-23T13:00:00.000Z",
    categoryId: "cat-disc-questions",
    followers: ["user-lily", "user-james"],
    updatedAt: "2026-09-24T08:30:00.000Z",
  },
  {
    id: "disc-5",
    title: "Looking for recommendations for a local contractor",
    body: "We're refreshing a small practice room in Bristol and need a reliable electrician who has worked with other members before. Happy to take recommendations privately or here if appropriate.",
    authorId: "user-sarah",
    date: "2026-09-16T11:20:00.000Z",
    categoryId: "cat-disc-recommendations",
    followers: ["user-sarah", "user-chloe"],
    updatedAt: "2026-09-18T15:45:00.000Z",
  },
  {
    id: "disc-6",
    title: "Can we improve the parking arrangements?",
    body: "Parking near Association House on event days is getting difficult. Has the committee considered a temporary arrangement with the neighbouring car park, or clearer guidance for members arriving by car?",
    authorId: "user-ethan",
    date: "2026-09-14T17:10:00.000Z",
    categoryId: "cat-disc-facilities",
    followers: ["user-ethan", "user-michael", "user-william"],
    updatedAt: "2026-09-22T10:00:00.000Z",
  },
  {
    id: "disc-7",
    title: "Best resources for newly accredited members?",
    body: "I've just completed accreditation and would love pointers on supervision, insurance and sensible first-client steps. What helped you most in your first year?",
    authorId: "user-noah",
    date: "2026-09-20T09:00:00.000Z",
    categoryId: "cat-disc-practice",
    followers: ["user-noah", "user-benjamin", "user-daniel", "user-grace"],
    updatedAt: "2026-09-25T16:30:00.000Z",
  },
  {
    id: "disc-8",
    title: "Online practice standards — what are others doing?",
    body: "I'm reviewing my online session setup (consent forms, privacy, platform choice). If you've settled on a clear approach, I'd appreciate hearing what works well for you.",
    authorId: "user-maya",
    date: "2026-09-18T12:45:00.000Z",
    categoryId: "cat-disc-practice",
    followers: ["user-maya", "user-thomas", "user-ruby"],
    updatedAt: "2026-09-21T18:00:00.000Z",
  },
  {
    id: "disc-9",
    title: "Book club picks for winter?",
    body: "Sophia and I are gathering suggestions for the winter reading circle. Fiction or professional titles both welcome — what should we put on the shortlist?",
    authorId: "user-sophia",
    date: "2026-09-22T15:20:00.000Z",
    categoryId: "cat-disc-general",
    followers: ["user-sophia", "user-freya", "user-olivia"],
    updatedAt: "2026-09-24T19:40:00.000Z",
  },
  {
    id: "disc-10",
    title: "Ideas for supporting members outside major cities",
    body: "As someone practising outside the big hubs, I'd love to hear ideas for better support — more regional hubs, travel bursaries for events, or stronger online community options?",
    authorId: "user-oscar",
    date: "2026-09-13T10:30:00.000Z",
    categoryId: "cat-disc-general",
    followers: ["user-oscar", "user-amelia", "user-helen", "user-isla"],
    updatedAt: "2026-09-20T12:15:00.000Z",
  },
];

export const comments: Comment[] = [
  {
    id: "cmt-1",
    discussionId: "disc-1",
    authorId: "user-chloe",
    body: "I booked Room B last month for a supervision pair — quiet, good natural light, and the booking system was straightforward.",
    date: "2026-09-21T14:00:00.000Z",
  },
  {
    id: "cmt-2",
    discussionId: "disc-1",
    authorId: "user-sarah",
    body: "Thanks Chloe. I'll try Room B. Did you find the kitchenette available for tea between sessions?",
    date: "2026-09-22T09:15:00.000Z",
  },
  {
    id: "cmt-3",
    discussionId: "disc-1",
    authorId: "user-michael",
    body: "Yes — the kitchenette remains open during lounge hours. Just leave it tidy for the next visitors.",
    date: "2026-09-24T14:20:00.000Z",
  },
  {
    id: "cmt-4",
    discussionId: "disc-2",
    authorId: "user-isla",
    body: "I'd love a short skill-share slot — 20 minutes each, three or four members. Keeps it light but useful.",
    date: "2026-09-20T10:00:00.000Z",
  },
  {
    id: "cmt-5",
    discussionId: "disc-2",
    authorId: "user-david",
    body: "Great idea. We'll note skill-shares on the planning list for the next events meeting.",
    date: "2026-09-21T11:30:00.000Z",
  },
  {
    id: "cmt-6",
    discussionId: "disc-2",
    authorId: "user-callum",
    body: "Could we also keep some unstructured outdoor time if the venue allows? Last year that was the highlight for many of us.",
    date: "2026-09-25T09:10:00.000Z",
  },
  {
    id: "cmt-7",
    discussionId: "disc-3",
    authorId: "user-sarah",
    body: "I'd join a Bristol / Bath walk if one starts. Happy to help with a first date.",
    date: "2026-09-17T12:00:00.000Z",
  },
  {
    id: "cmt-8",
    discussionId: "disc-3",
    authorId: "user-amelia",
    body: "Northern Ireland would welcome something similar — even quarterly would be lovely.",
    date: "2026-09-18T08:40:00.000Z",
  },
  {
    id: "cmt-9",
    discussionId: "disc-3",
    authorId: "user-callum",
    body: "Wonderful. I'll draft a simple signup note and share it once we have a couple of regional leads.",
    date: "2026-09-23T11:05:00.000Z",
  },
  {
    id: "cmt-10",
    discussionId: "disc-4",
    authorId: "user-james",
    body: "Confirmed — Birmingham regional meeting is still 12 October, 10:00 at the community centre near New Street. Agenda goes out next week.",
    date: "2026-09-24T08:30:00.000Z",
  },
  {
    id: "cmt-11",
    discussionId: "disc-5",
    authorId: "user-chloe",
    body: "I used a local electrician in South Bristol last year for a similar job — happy to share the name if you message me.",
    date: "2026-09-17T16:00:00.000Z",
  },
  {
    id: "cmt-12",
    discussionId: "disc-5",
    authorId: "user-sarah",
    body: "That would be perfect, thank you Chloe.",
    date: "2026-09-18T15:45:00.000Z",
  },
  {
    id: "cmt-13",
    discussionId: "disc-6",
    authorId: "user-michael",
    body: "We're speaking with the neighbouring car park about event-day rates. Guidance will go out before the AGM.",
    date: "2026-09-15T09:00:00.000Z",
  },
  {
    id: "cmt-14",
    discussionId: "disc-6",
    authorId: "user-william",
    body: "Clearer signage on arrival would help too — first-time visitors often miss the side entrance.",
    date: "2026-09-16T14:20:00.000Z",
  },
  {
    id: "cmt-15",
    discussionId: "disc-6",
    authorId: "user-ethan",
    body: "Appreciate the update, Michael. Looking forward to the guidance note.",
    date: "2026-09-22T10:00:00.000Z",
  },
  {
    id: "cmt-16",
    discussionId: "disc-7",
    authorId: "user-benjamin",
    body: "Start with a good supervisor and modest caseload. The association's new-member pack has a solid checklist — ask Isla if you haven't received it.",
    date: "2026-09-20T15:00:00.000Z",
  },
  {
    id: "cmt-17",
    discussionId: "disc-7",
    authorId: "user-daniel",
    body: "I run a monthly supervision group with a couple of spaces from November if that helps.",
    date: "2026-09-21T10:45:00.000Z",
  },
  {
    id: "cmt-18",
    discussionId: "disc-7",
    authorId: "user-grace",
    body: "Insurance comparison was the most confusing bit for me — speak to two brokers who understand complementary therapy.",
    date: "2026-09-22T13:10:00.000Z",
  },
  {
    id: "cmt-19",
    discussionId: "disc-7",
    authorId: "user-noah",
    body: "This is all incredibly helpful — thank you. I'll reach out to Isla and Daniel this week.",
    date: "2026-09-25T16:30:00.000Z",
  },
  {
    id: "cmt-20",
    discussionId: "disc-8",
    authorId: "user-thomas",
    body: "I use a UK-based video platform with a BAA-style agreement and keep consent forms separate. Happy to share a template outline.",
    date: "2026-09-19T09:30:00.000Z",
  },
  {
    id: "cmt-21",
    discussionId: "disc-8",
    authorId: "user-ruby",
    body: "Same here. I also note in my privacy notice that sessions are not recorded unless agreed in writing.",
    date: "2026-09-20T11:00:00.000Z",
  },
  {
    id: "cmt-22",
    discussionId: "disc-8",
    authorId: "user-maya",
    body: "Thank you both — a template outline would be wonderful, Thomas.",
    date: "2026-09-21T18:00:00.000Z",
  },
  {
    id: "cmt-23",
    discussionId: "disc-9",
    authorId: "user-freya",
    body: "I'd nominate a gentle professional title on grief and presence — I can send the full name if useful.",
    date: "2026-09-23T08:00:00.000Z",
  },
  {
    id: "cmt-24",
    discussionId: "disc-9",
    authorId: "user-olivia",
    body: "A short novel that sparked good conversation last year was popular with the education-focused members. I'll dig out the title.",
    date: "2026-09-24T19:40:00.000Z",
  },
  {
    id: "cmt-25",
    discussionId: "disc-10",
    authorId: "user-amelia",
    body: "Travel bursaries for the conference would make a real difference for NI and rural members.",
    date: "2026-09-14T12:00:00.000Z",
  },
  {
    id: "cmt-26",
    discussionId: "disc-10",
    authorId: "user-helen",
    body: "Noted for the committee. Stronger online options are also on the agenda after the AGM.",
    date: "2026-09-15T16:30:00.000Z",
  },
  {
    id: "cmt-27",
    discussionId: "disc-10",
    authorId: "user-isla",
    body: "Regional welcome packs for new members outside London are something we can improve quickly.",
    date: "2026-09-18T09:45:00.000Z",
  },
  {
    id: "cmt-28",
    discussionId: "disc-10",
    authorId: "user-oscar",
    body: "Appreciate everyone taking this seriously. Looking forward to progress after the AGM.",
    date: "2026-09-20T12:15:00.000Z",
  },
  {
    id: "cmt-29",
    discussionId: "disc-2",
    authorId: "user-harry",
    body: "I'll collate suggestions into a short summary for the events subcommittee next week.",
    date: "2026-09-22T14:00:00.000Z",
  },
  {
    id: "cmt-30",
    discussionId: "disc-4",
    authorId: "user-lily",
    body: "Perfect — thank you James. I'll book my train today.",
    date: "2026-09-24T09:00:00.000Z",
  },
  {
    id: "cmt-31",
    discussionId: "disc-7",
    authorId: "user-isla",
    body: "Noah — I've just resent the welcome pack to your member email. Do shout if anything is missing.",
    date: "2026-09-23T11:20:00.000Z",
  },
  {
    id: "cmt-32",
    discussionId: "disc-1",
    authorId: "user-george",
    body: "Room C has the better whiteboard if you're planning any teaching notes during supervision.",
    date: "2026-09-23T16:50:00.000Z",
  },
];

export const events: EventItem[] = [
  {
    id: "evt-1",
    name: "Annual General Meeting",
    description:
      "Official AGM including annual report, financial statements, committee elections and member Q&A. Remote attendance available.",
    date: "2026-10-18",
    time: "10:00",
    location: "Association House, London (and online)",
  },
  {
    id: "evt-2",
    name: "Members' Dinner",
    description:
      "An evening dinner for members following the autumn workshop series. Informal dress. Places are limited.",
    date: "2026-11-14",
    time: "19:00",
    location: "The Riverside Room, Manchester",
  },
  {
    id: "evt-3",
    name: "Community Meeting — Midlands",
    description:
      "Open community meeting for Midlands members: regional updates, peer introductions and light refreshments.",
    date: "2026-10-12",
    time: "10:00",
    location: "Community Centre, Birmingham",
  },
  {
    id: "evt-4",
    name: "Introductory Practice Workshop",
    description:
      "A half-day workshop for newly accredited members covering practical first-year considerations and peer connection.",
    date: "2026-11-08",
    time: "09:30",
    location: "Association House, London",
  },
  {
    id: "evt-5",
    name: "Summer Social 2026",
    description:
      "Our annual summer gathering with networking, light skill shares and afternoon tea. A lovely day in Bath.",
    date: "2026-07-19",
    time: "13:00",
    location: "Assembly Rooms, Bath",
  },
  {
    id: "evt-6",
    name: "Christmas Event",
    description:
      "Seasonal gathering for members and guests. Short seasonal address, refreshments and optional carol moment.",
    date: "2026-12-12",
    time: "16:00",
    location: "Association House, London",
  },
];

export const notifications: Notification[] = [
  {
    id: "ntf-1",
    userId: "user-sarah",
    type: "announcement",
    title: "New association announcement",
    message: "A new association announcement has been published: Important maintenance notice.",
    date: "2026-09-20T08:05:00.000Z",
    read: false,
    relatedType: "news",
    relatedId: "post-5",
  },
  {
    id: "ntf-2",
    userId: "user-sarah",
    type: "comment_on_followed",
    title: "New comment on a discussion you follow",
    message: "Michael commented on “Has anyone used the new Association House facilities?”",
    date: "2026-09-24T14:21:00.000Z",
    read: false,
    relatedType: "discussion",
    relatedId: "disc-1",
  },
  {
    id: "ntf-3",
    userId: "user-sarah",
    type: "event",
    title: "Upcoming event reminder",
    message: "The Annual General Meeting is on 18 October. Registration closes soon.",
    date: "2026-09-22T09:00:00.000Z",
    read: true,
    relatedType: "event",
    relatedId: "evt-1",
  },
  {
    id: "ntf-4",
    userId: "user-sarah",
    type: "news",
    title: "Newsletter published",
    message: "The Autumn edition of the association newsletter is now available.",
    date: "2026-09-15T10:05:00.000Z",
    read: true,
    relatedType: "news",
    relatedId: "post-6",
  },
  {
    id: "ntf-5",
    userId: "user-david",
    type: "comment_on_own",
    title: "New comment on your discussion",
    message: "Callum commented on “Suggestions for the summer event”.",
    date: "2026-09-25T09:11:00.000Z",
    read: false,
    relatedType: "discussion",
    relatedId: "disc-2",
  },
  {
    id: "ntf-6",
    userId: "user-helen",
    type: "announcement",
    title: "New association announcement",
    message: "Important maintenance notice for Association House has been published.",
    date: "2026-09-20T08:05:00.000Z",
    read: false,
    relatedType: "news",
    relatedId: "post-5",
  },
  {
    id: "ntf-7",
    userId: "user-michael",
    type: "comment_on_followed",
    title: "New comment on a discussion you follow",
    message: "Ethan commented on “Can we improve the parking arrangements?”",
    date: "2026-09-22T10:01:00.000Z",
    read: true,
    relatedType: "discussion",
    relatedId: "disc-6",
  },
  {
    id: "ntf-8",
    userId: "user-sarah",
    type: "comment_on_own",
    title: "New comment on your discussion",
    message: "Chloe commented on “Looking for recommendations for a local contractor”.",
    date: "2026-09-17T16:01:00.000Z",
    read: true,
    relatedType: "discussion",
    relatedId: "disc-5",
  },
];

export const submissions: Submission[] = [
  {
    id: "sub-1",
    title: "Could we organise a members' walking group?",
    content:
      "I'd like to propose a gentle monthly walking group for members — informal, welcoming, and open to all fitness levels. Happy to help coordinate a Bristol starting point.",
    categoryId: "cat-disc-general",
    type: "discussion",
    authorId: "user-sarah",
    date: "2026-09-24T10:00:00.000Z",
    status: "pending",
  },
  {
    id: "sub-2",
    title: "Request: clearer guidance for first-year insurance",
    content:
      "Many newly accredited members find insurance confusing. Could the association publish a short plain-English guide with common questions?",
    categoryId: "cat-disc-practice",
    type: "discussion",
    authorId: "user-lily",
    date: "2026-09-23T14:20:00.000Z",
    status: "pending",
  },
  {
    id: "sub-3",
    title: "Regional meet-up proposal for Edinburgh",
    content:
      "I'd like to submit a news item inviting Scotland members to a November meet-up in Edinburgh. Venue tentatively held.",
    categoryId: "cat-news-community",
    type: "news",
    authorId: "user-olivia",
    date: "2026-09-22T11:45:00.000Z",
    status: "pending",
  },
  {
    id: "sub-4",
    title: "Shared client resources folder idea",
    content:
      "Would members find value in a moderated shared folder of non-copyrighted client worksheets? Looking for interest before we ask the committee.",
    categoryId: "cat-disc-practice",
    type: "discussion",
    authorId: "user-george",
    date: "2026-09-21T09:30:00.000Z",
    status: "pending",
  },
  {
    id: "sub-5",
    title: "Volunteer call for Christmas Event",
    content:
      "We will need stewards and a small welcome team for the December Christmas Event. Please consider publishing a short call for volunteers.",
    categoryId: "cat-news-events",
    type: "news",
    authorId: "user-harry",
    date: "2026-09-20T16:10:00.000Z",
    status: "pending",
  },
];

export function createDefaultPreferences(): Record<string, NotificationPreference> {
  const prefs: Record<string, NotificationPreference> = {};
  for (const member of members) {
    prefs[member.id] = { ...DEFAULT_PREFERENCES };
  }
  return prefs;
}

export function getSeedState() {
  return {
    currentUserId: null as string | null,
    members: structuredClone(members),
    posts: structuredClone(posts),
    discussions: structuredClone(discussions),
    comments: structuredClone(comments),
    events: structuredClone(events),
    notifications: structuredClone(notifications),
    submissions: structuredClone(submissions),
    preferences: createDefaultPreferences(),
    resourceActivity: [],
  };
}
